name: Build and Release Debian Package

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create Dockerfile
      run: |
        cat <<EOF > Dockerfile
        # syntax=docker/dockerfile:1
        FROM --platform=linux/arm64 debian:bullseye as base

        RUN apt-get update && \
            apt-get install -y \
              build-essential \
              cmake \
              devscripts \
              debhelper \
              dh-exec \
              libtool

        COPY . /src

        FROM base as deb_builder
        WORKDIR /src
        RUN debuild -us -uc -aarm64 -b
        EOF

    - name: Build Debian Package
      run: |
        docker buildx build --platform linux/arm64 -o type=local,dest=output --target deb_builder -f Dockerfile .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Debian Packages
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          ./output/librockchip-mpp-dev_1.5.0-1_arm64.deb
        asset_name: |
          librockchip-mpp-dev_1.5.0-1_arm64.deb
        asset_content_type: |
          application/octet-stream

    - name: Upload Debian Packages
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          ./output/librockchip-mpp1_1.5.0-1_arm64.deb
        asset_name: |
          librockchip-mpp1_1.5.0-1_arm64.deb
        asset_content_type: |
          application/octet-stream

    - name: Upload Debian Packages
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          ./output/librockchip-vpu0_1.5.0-1_arm64.deb
        asset_name: |
          librockchip-vpu0_1.5.0-1_arm64.deb
        asset_content_type: |
          application/octet-stream

    - name: Upload Debian Packages
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          ./output/rockchip-mpp-demos_1.5.0-1_arm64.deb
        asset_name: |
          rockchip-mpp-demos_1.5.0-1_arm64.deb
        asset_content_type: |
          application/octet-stream
